apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  app.kubernetes.io/part-of: prometheus-node-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-node-exporter
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  app.kubernetes.io/part-of: prometheus-kube-state-metric
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      interval: 15s
